# Generated by Django 2.1 on 2018-08-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0062_auto_20180820_1446'),
        ('mainapp', '0076_auto_20180822_1220'),
    ]

    operations = [
    ]
